# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-13 19:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=2)),
                ('listing_type', models.CharField(choices=[('OF', 'Offer'), ('RQ', 'Request'), ('TC', 'Teach'), ('LR', 'Learn'), ('GT', 'Gift'), ('GL', 'Goal')], max_length=2)),
                ('photo', models.ImageField(upload_to='media')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
