# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('listings', '0003_auto_20161213_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='subcategories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.SubCategories'),
        ),
    ]
