# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-15 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categories_text', models.CharField(max_length=220)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Categories')),
            ],
        ),
    ]
